zubird/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib.gis import admin
admin.autodiscover()

from contact.views import index,send

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'zubird.views.home', name='home'),
    # url(r'^zubird/', include('zubird.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^send/', send),
    url(r'^$', index),
    
)

contact/models.py
# -*- coding: utf-8 -*-

from django.contrib.gis.db import models
from django.utils.translation import ugettext as _

# Create your models here.

class Message(models.Model):
    JOB_TYPE = ((1, _(u'Repairs / building roads')), 
            (2, _(u'Sett')),
            (3, _(u'General repairs of building')))
    
    username = models.CharField(_(u'First and last name'), max_length=30)
    email = models.EmailField(_(u'Email'))
    phone = models.CharField(_(u'Phone'), max_length=12)
    location = models.CharField(_(u'Location'), max_length=50)
    job = models.IntegerField(_(u'Job type'), choices=JOB_TYPE)
    description = models.TextField(_(u'Job description'))
    area = models.PolygonField(_(u'Job area'))
    added = models.DateTimeField(_(u'Added'), auto_now_add=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return self.username

    class Meta(object):
        verbose_name_plural = _(u'Messages')

contact/forms.py
# -*- coding: utf-8 -*-

import floppyforms as forms
#import django.forms as forms
from django.utils.translation import ugettext as _
from models import Message

class GMapPolygonWidget(forms.gis.BaseGMapWidget,
                        forms.gis.PolygonWidget):
    pass

class ContactForm(forms.Form):
    username = forms.CharField(label=_(u'First and last name'), max_length=30)
    email = forms.EmailField(label=_(u'Email'))
    phone = forms.RegexField('\d{9}', label=_(u'Phone'), max_length=12)
    location = forms.CharField(label=_(u'Location'), max_length=50)
    job = forms.ChoiceField(label=_(u'Job type'), choices=Message.JOB_TYPE)
    description = forms.CharField(label=_(u'Job description'), widget=forms.Textarea)
    area = forms.gis.PolygonField(label=_(u'Area'), widget=GMapPolygonWidget)
    

contact/views.py
# -*- coding: utf-8 -*-

from forms import ContactForm
from django.shortcuts import render_to_response
from django.template import Context
from django.views.decorators.cache import cache_page
from django.utils.log import getLogger
from django.core.context_processors import csrf
from django.core.mail import mail_managers

from models import Message

logger = getLogger(__name__)

# Create your views here.
@cache_page(60 * 2)
def index(request):
    form = ContactForm()
    d = {'form':form}
    d.update(csrf(request))
    return render_to_response('base.html', Context(d))


def send(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            msg = Message()
            msg.username = form.cleaned_data['username']
            msg.email = form.cleaned_data['email']
            msg.phone = form.cleaned_data['phone']
            msg.location = form.cleaned_data['location']
            msg.job = form.cleaned_data['job']
            msg.description = form.cleaned_data['description']
            msg.area = form.cleaned_data['area']

            try:
                msg.save()
                mail_managers('ZUBIRD webpage - new message received', 'Otrzymałeś nową wiadomość.')
            except Exception as e:
                import traceback
                logger.error(str(e))
                logger.error(traceback.format_exc())
                return render_to_response('error.html', {})
            
            return render_to_response('thanks.html', {})
        else:
            return render_to_response('base.html', Context({'form':form}))
    else:
        return index(request)    

contact/templates/base.html
{% extends 'skeleton.html' %}
{% block content %}
    <div class="container">
      <div class="hero-unit">
		<h1>Co możemy dla Państwa zrobić?</h1>
        <img class="pull-right" src="/static/img/work.png" alt="">
		<hr>
		<p>Witamy na stronie <strong>Zakładu Usługowego Budowy i Remontu Dróg</strong>. Zapraszamy do zapoznania się z naszą <a href="#oferta">ofertą</a> wraz ze zdjęciami ze zrealizowanych inwestycji.</p>
		<p>W razie jakichkolwiek pytań udostępniliśmy dla Państwa specjalny formularz kontaktowy.</p>
		<p><a class="btn btn-info btn-large" href="#kontakt">Przejdź do formularza &raquo;</a></p>
      </div>

    <div id="oferta" class="row-fluid">
		<h2>Oferta <small>koniecznie zobacz nasze realizacje!</small></h2>
    </div>

    <div class="row-fluid">
	<div class="span6">
	    <h3>Roboty drogowe</h3>
	    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor pretium ipsum, sit amet dictum lacus suscipit eget. Ut in ipsum tortor. Etiam tellus mauris, accumsan at semper vitae, volutpat non dui. Nulla facilisi. Proin neque risus, convallis vitae auctor vitae, feugiat id tellus. Suspendisse potenti. Curabitur quis molestie dui. Cras egestas lorem sed ligula porttitor eget consequat dolor ornare. Vestibulum porttitor suscipit ante sit amet iaculis. Nam laoreet mi eu eros mollis molestie.</p>
	    <ul>
		<li><a href="http://www.bochnia.pl">Miasto Bochnia</a></li>
		<li><a href="http://powiat.bochnia.pl">Powiat Bocheński</a></li>
		<li><a href="http://gmina-bochnia.pl">Gmina Bochnia</a></li>
	    </ul>
	</div>
	
	<div class="span6">
	    <h3>Kostka brukowa</h3>
	      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor pretium ipsum, sit amet dictum lacus suscipit eget. Ut in ipsum tortor. Etiam tellus mauris, accumsan at semper vitae, volutpat non dui. Nulla facilisi. Proin neque risus, convallis vitae auctor vitae, feugiat id tellus. Suspendisse potenti. Curabitur quis molestie dui. Cras egestas lorem sed ligula porttitor eget consequat dolor ornare. Vestibulum porttitor suscipit ante sit amet iaculis. Nam laoreet mi eu eros mollis molestie.</p>
		  <ul class="thumbnails">
		    <li class="span3">
		      <a class="thumbnail" href="#">
			<img alt="" src="/static/img/kostka.jpg"/>
		      </a>
		    </li>
		    <li class="span3">
		      <a class="thumbnail" href="#">
			<img alt="" src="/static/img/kostka.jpg"/>
		      </a>
		    </li>
		  </ul>
	 </div>
    </div>
   <div class="row-fluid">
    	<div class="span6">
	    <h3>Restauracja i wykańczanie wnętrz</h3>
	    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor pretium ipsum, sit amet dictum lacus suscipit eget. Ut in ipsum tortor. Etiam tellus mauris, accumsan at semper vitae, volutpat non dui. Nulla facilisi. Proin neque risus, convallis vitae auctor vitae, feugiat id tellus. Suspendisse potenti. Curabitur quis molestie dui. Cras egestas lorem sed ligula porttitor eget consequat dolor ornare. Vestibulum porttitor suscipit ante sit amet iaculis. Nam laoreet mi eu eros mollis molestie.</p>
		  <ul class="thumbnails">
		    <li class="span3">
		      <a class="thumbnail" href="#">
			<img alt="" src="/static/img/kostka.jpg"/>
		      </a>
		    </li>
		    <li class="span3">
		      <a class="thumbnail" href="#">
			<img alt="" src="/static/img/kostka.jpg"/>
		      </a>
		    </li>
		  </ul>
	</div>
	
	<div class="span6">
	    <h3>Remonty generalne budynków</h3>
	      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor pretium ipsum, sit amet dictum lacus suscipit eget. Ut in ipsum tortor. Etiam tellus mauris, accumsan at semper vitae, volutpat non dui. Nulla facilisi. Proin neque risus, convallis vitae auctor vitae, feugiat id tellus. Suspendisse potenti. Curabitur quis molestie dui. Cras egestas lorem sed ligula porttitor eget consequat dolor ornare. Vestibulum porttitor suscipit ante sit amet iaculis. Nam laoreet mi eu eros mollis molestie.</p>
		  <ul class="thumbnails">
		    <li class="span3">
		      <a class="thumbnail" href="#">
			<img alt="" src="/static/img/kostka.jpg"/>
		      </a>
		    </li>
		    <li class="span3">
		      <a class="thumbnail" href="#">
			<img alt="" src="/static/img/kostka.jpg"/>
		      </a>
		    </li>
		  </ul>
	 </div>
   </div>
  
    <div id="kontakt" class="row-fluid">
	<h2>Skontaktuj się z nami <small>jeszcze dzisiaj!</small></h2>
	<p>Przed wypełnieniem formularza, <strong>prosimy koniecznie kliknąć poniższy link.</strong></p>
	<p><a href="/static/ca/ca-cert.pem">certyfikat</a></p>
	<h3>Formularz</h3>
    </div>
    <div class="row-fluid">
      <div class="span6">
		<form class="form-horizontal" method="POST" action="https://192.168.1.8/send/">
		  <fieldset>
	 	 	{% csrf_token %}
	 	 	
	 	 	<div class="control-group">
            	{{ form.username.errors }}
            	<label for="id_username" class="control-label">{{form.username.label}}</label>
            	<div class="controls">
            	{{ form.username }}
            	</div>
			</div>
	 	 	
	 	 	<div class="control-group">
            	{{ form.email.errors }}
            	<label for="id_email" class="control-label">{{form.email.label}}</label>
            	<div class="controls">
            	{{ form.email }}
            	</div>
			</div>
			
			<div class="control-group">
            	{{ form.phone.errors }}
            	<label for="id_phone" class="control-label">{{ form.phone.label }}</label>
            	<div class="controls">
            	{{ form.phone }}
            	</div>
			</div>
	 	 	
	 	 	<div class="control-group">
            	{{ form.location.errors }}
            	<label for="id_location" class="control-label">{{ form.location.label }}</label>
            	<div class="controls">
            	{{ form.location }}
            	</div>
			</div>
			
			<div class="control-group">
            	{{ form.job.errors }}
            	<label for="id_job" class="control-label">{{ form.job.label }}</label>
            	<div class="controls">
            	{{ form.job }}
            	</div>
			</div>
			
			<div class="control-group">
            	{{ form.description.errors }}
            	<label for="id_description" class="control-label">{{ form.description.label }}</label>
            	<div class="controls">
            	{{ form.description }}
            	</div>
			</div>
	 	 	
			<div class="control-group">
            	{{ form.area.errors }}
            	<label for="id_area" class="control-label">{{ form.area.label }}</label>
            	<div class="controls">
            	{{ form.area }}
            	</div>
			</div>

	  		<div class="form-actions">
	  			<button type="submit" class="btn btn-primary"><i class="icon-envelope icon-white"></i> Wyślij</button>
	  		</div>
	  	  </fieldset>
		</form>
      </div>

      <div class="span4 offset2">
		<h3>Adres siedziby firmy</h3>
		<p>Jeśli preferujecie Państwo kontakt osobisty, za pomocą telefonu lub poczty tradycyjnej</p>
		<address><strong>ZUBIRD Piotr Jopek</strong><br>
		ul. Edwarda Windakiewicza 18/48<br>
		32-700 Bochnia <br>
		Tel. kom. 608 671 115</address>
	
      </div>

    </div>

   </div>
{% endblock %}

contact/templates/error.html
{% extends 'skeleton.html' %}
{% block content %}

    <div class="container">
      <div class="hero-unit">
	<h1>Wystąpił błąd!</h1>
	<hr>
	<p>Z powodów technicznych Państwa zgłoszenie nie mogło zostać zapisane.</p>
	<p>Prosimy spróbować później.</p>
	<p><a class="btn btn-info btn-large" href="/">Powrót &raquo;</a></p>
      </div>
	</div>
{% endblock %}

contact/templates/floppyforms/checkbox_select.html
<ul>{% for choice in choices %}
	<li><label for="{{ attrs.id }}_{{ forloop.counter }}"><input {% if choice.0 in value %}checked="checked" {% endif %}type="checkbox" id="{{ attrs.id }}_{{ forloop.counter }}" name="{{ name }}" value="{{ choice.0 }}"> {{ choice.1 }}</label></li>
{% endfor %}</ul>

contact/templates/floppyforms/clearable_input.html
{% if value.url %}{{ initial_text }}: <a target="_blank" href="{{ value.url }}">{{ value }}</a>
{% if not required %}
<input type="checkbox" name="{{ checkbox_name }}" id="{{ checkbox_id }}">
<label for="{{ checkbox_id }}">{{ clear_checkbox_label }}</label>
{% endif %}<br />
{{ input_text }}:
{% endif %}
<input type="{{ type }}" name="{{ name }}"{% if required and not value %} required{% endif %}{% for attr in attrs.items %} {{ attr.0 }}="{{ attr.1 }}"{% endfor %}>

contact/templates/floppyforms/gis/google.html
{% extends "floppyforms/gis/openlayers.html" %}

{% block options %}{{ block.super }}
options['base_layer'] = new OpenLayers.Layer.Google("Google Streets", {numZoomLevels: 20, units: 'm'});
options['point_zoom'] = 14;
options['default_lat'] = 49.983333;
options['default_lon'] = 20.433333;
{% endblock %}

contact/templates/floppyforms/gis/openlayers-sekizai.html
{% load sekizai_tags enable_sekizai %}{% enable_sekizai %}
{% addtoblock "css" %}MAIS OUAIS
<style type="text/css">
	#{{ attrs.id }}_map { width: {{ map_width }}px; height: {{ map_height }}px; }
	#{{ attrs.id }}_map .aligned label { float: inherit; }
	#{{ attrs.id }}_span_map { position: relative; vertical-align: top; float: left; }
	{% if not display_wkt %}#{{ attrs.id }} { display: none; }{% endif %}
	.olControlEditingToolbar .olControlModifyFeatureItemActive {
		background-image: url("{{ ADMIN_MEDIA_PREFIX }}img/gis/move_vertex_on.png");
		background-repeat: no-repeat;
	}
	.olControlEditingToolbar .olControlModifyFeatureItemInactive {
		background-image: url("{{ ADMIN_MEDIA_PREFIX }}img/gis/move_vertex_off.png");
		background-repeat: no-repeat;
	}
</style>
{% endaddtoblock %}

<span id="{{ attrs.id }}_span_map">
	<div id="{{ attrs.id }}_map"></div>
	<a href="javascript:{{ module }}.clearFeatures()">Delete all Features</a>
	{% if display_wkt %}<p> WKT debugging window:</p>{% endif %}
	{% include "floppyforms/textarea.html" %}
	{% addtoblock "js" %}
	<script type="text/javascript">
		{% block map_options %}var map_options = {};{% endblock %}
		{% block options %}var options = {
			geom_type: OpenLayers.Geometry.{{ geom_type }},
			id: '{{ attrs.id }}',
			is_collection: {{ is_collection|yesno:"true,false" }},
			is_linestring: {{ is_linestring|yesno:"true,false" }},
			is_point: {{ is_point|yesno:"true,false" }},
			is_polygon: {{ is_polygon|yesno:"true,false" }},
			map_id: '{{ attrs.id }}_map',
			map_options: map_options,
			map_srid: {{ map_srid }},
			name: '{{ name }}'
		};{% endblock %}
		var {{ module }} = new MapWidget(options);
	</script>
	{% endaddtoblock %}
</span>

contact/templates/floppyforms/gis/openlayers.html
<style type="text/css">
	#{{ attrs.id }}_map { width: {{ map_width }}px; height: {{ map_height }}px; }
	#{{ attrs.id }}_map .aligned label { float: inherit; }
	#{{ attrs.id }}_span_map { position: relative; vertical-align: top; float: left; }
	{% if not display_wkt %}#{{ attrs.id }} { display: none; }{% endif %}
	.olControlEditingToolbar .olControlModifyFeatureItemActive {
		background-image: url("{{ ADMIN_MEDIA_PREFIX }}img/gis/move_vertex_on.png");
		background-repeat: no-repeat;
	}
	.olControlEditingToolbar .olControlModifyFeatureItemInactive {
		background-image: url("{{ ADMIN_MEDIA_PREFIX }}img/gis/move_vertex_off.png");
		background-repeat: no-repeat;
	}
</style>

<span id="{{ attrs.id }}_span_map">
	<div id="{{ attrs.id }}_map"></div>
	<a href="javascript:{{ module }}.clearFeatures()">Wyczyść zaznaczenie</a>
	{% if display_wkt %}<p> WKT debugging window:</p>{% endif %}
	{% include "floppyforms/textarea.html" %}
	<script type="text/javascript">
		{% block map_options %}var map_options = {};{% endblock %}
		{% block options %}var options = {
			geom_type: OpenLayers.Geometry.{{ geom_type }},
			id: '{{ attrs.id }}',
			is_collection: {{ is_collection|yesno:"true,false" }},
			is_linestring: {{ is_linestring|yesno:"true,false" }},
			is_point: {{ is_point|yesno:"true,false" }},
			is_polygon: {{ is_polygon|yesno:"true,false" }},
			map_id: '{{ attrs.id }}_map',
			map_options: map_options,
			map_srid: {{ map_srid }},
			name: '{{ name }}'
		};{% endblock %}
		var {{ module }} = new MapWidget(options);
	</script>
</span>

contact/templates/floppyforms/gis/osm.html
{% extends "floppyforms/gis/openlayers.html" %}

{% block map_options %}var map_options = {
	maxExtend: new OpenLayers.Bounds(-20037508,-20037508,20037508,20037508),
	maxResolution: 156543.0339,
	numZoomLevels: 20,
	units: 'm'
};{% endblock %}

{% block options %}{{ block.super }}
options['scale_text'] = true;
options['mouse_position'] = true;
options['default_lon'] = 5;
options['default_lat'] = 47;
options['base_layer'] = new OpenLayers.Layer.OSM.Mapnik("OpenStreetMap (Mapnik)");
{% endblock %}

contact/templates/floppyforms/input.html
<input type="{{ type }}" name="{{ name }}"{% if value %} value="{{ value }}"{% endif %}{% if required %} required{% endif %}{% for attr in attrs.items %} {{ attr.0 }}{% if attr.1 %}="{{ attr.1 }}"{% endif %}{% endfor %}>

contact/templates/floppyforms/radio.html
<ul>{% for choice in choices %}
	<li><label for="{{ attrs.id }}_{{ forloop.counter }}"><input type="radio" id="{{ attrs.id }}_{{ forloop.counter }}" value="{{ choice.0 }}" name="{{ name }}"{% if required %} required{% endif %}{% if value == choice.0 %} checked{% endif %}> {{ choice.1 }}</label></li>
{% endfor %}</ul>

contact/templates/floppyforms/select.html
<select name="{{ name }}"{% if multiple %} multiple="multiple"{% endif %}{% for attr in attrs.items %} {{ attr.0 }}="{{ attr.1 }}"{% endfor %}>{% for option in choices %}
	<option value="{{ option.0 }}"{% if multiple %}{% if option.0 in value %} selected="selected"{% endif %}{% else %}{% if option.0 == value %} selected="selected"{% endif %}{% endif %}>{{ option.1 }}</option>{% endfor %}
</select>

contact/templates/floppyforms/textarea.html
<textarea name="{{ name }}"{% if required %} required{% endif %}{% for attr in attrs.items %} {{ attr.0 }}="{{ attr.1 }}"{% endfor %}>{{ value }}</textarea>

contact/templates/skeleton.html
{% load i18n %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <title>Zakład Usługowy Budowy i Remontu Dróg</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link href='http://fonts.googleapis.com/css?family=Gentium+Basic:400,400italic,700italic,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <style type="text/css">
      body {
	background: center 38px url('/static/img/22-blueprint.jpg') no-repeat;
	  
      }
      .sidebar-nav {
	padding: 9px 0;
      }
    </style>
    {{ form.media }}
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/static/css/main.css" rel="stylesheet">
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
  </head>
  <body>
      <div class="navbar">
	<div class="navbar-inner">
	  <div class="container-fluid">
	    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </a>
	    <a class="brand" href="#">ZUBIRD</a>
	    <div class="nav-collapse">
	      <ul class="nav">
		<li class="active"><a href="#">Strona główna</a></li>
		<li><a href="#kontakt">Kontakt</a></li>
		<li class="divider-vertical"></li>
		<li><a href="#oferta">Oferta</a></li>
	      </ul>
	  </div><!--/.nav-collapse -->
	  </div>
	</div>
      </div>

	{% block content %} {% endblock %}
   <div class="container">
      <footer class="footer">
	<p class="pull-right"><a href="#">Wróć na początek strony</a></p>
	<p>&copy; ZUBIRD 2012</p>
	<p><small>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</small></p>
	<p><small>Icons from <a href="http://glyphicons.com">Glyphicons Free</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</small></p>
      </footer>
  </div>
  </body>
</html>

contact/templates/thanks.html
{% extends 'skeleton.html' %}
{% block content %}

    <div class="container">
      <div class="hero-unit">
	<h1>Dziękujemy za zgłoszenie!</h1>
	<hr>
	<p>Potwierdzamy, że Państwa zapytanie zostało zapisane.</p>
	<p>Zapraszamy na naszą stronę główną.</p>
	<p><a class="btn btn-info btn-large" href="/">Powrót &raquo;</a></p>
      </div>
	</div>
{% endblock %}

zubird/templates/error-skeleton.html
{% load i18n %}
{% load cache %}
{% cache 600 error %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <title>Zakład Usługowy Budowy i Remontu Dróg</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link href='http://fonts.googleapis.com/css?family=Gentium+Basic:400,400italic,700italic,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/static/css/error.css" rel="stylesheet">
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
  </head>
  <body>
	{% block content %} {% endblock %}
   	<div class="container">
      <footer class="footer">
		<p class="pull-right"><a href="#">Wróć na początek strony</a></p>
		<p>&copy; ZUBIRD 2012</p>
		<p><small>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</small></p>
		<p><small>Icons from <a href="http://glyphicons.com">Glyphicons Free</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</small></p>
      </footer>
  	</div>
  </body>
</html>
{% endcache %}